### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by qwalkerbrite** [enix223/react-native-open-settings#1]
This is a great idea because this type of plugin doesn't exist. However, its broken down to the core. Will try and contribute but one thing one needs to clarify is permissions in IOS and perhaps its a deal breaker for plugin

**Comment by enix223** [comment]
Thank you for your message, iOS does not support navigate to specific setting page for the latest os version.

For more detail pls refer to: https://github.com/FifiTheBulldog/ios-settings-urls/issues/9
